name             'kms'
maintainer       'Brian Oldfield'
maintainer_email 'brian@oldfield.io'
license          'apache2'
description      'Provides kms resource for retrieving secrets from the S3/KMS'
long_description 'Provides kms resource for retrieving secrets from the S3/KMS'
source_url       'https://github.com/boldfield/kms-chef'
issues_url       'https://github.com/boldfield/kms-chef/issues'
version          '0.1.0'
